language: node_js
sudo: true
dist: trusty
cache:
  directories:
  #- node_modules

node_js:
  - "14"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_success:
  # Send coverage data to Coveralls
  - cat ./coverage/core/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  # send code coverage to codeclimate
  - npm run codeclimate
  - npm run all
