version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.4
jobs:
  build:
    docker:
      - image: cimg/node:14.19-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - browser-tools/install-chrome
      - checkout

      - restore_cache:
          name: Restore Package Cache
          keys:
            - packages-{{ .Branch }}-{{ checksum "package-lock.json" }}

      - run: npm ci

      - save_cache:
          name: Save Package Cache
          key: packages-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules/

      - run: npm run all
