version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14-stretch-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - checkout

      - restore_cache:
          name: Restore Package Cache
          keys:
            - packages-{{ .Branch }}-{{ checksum "package-lock.json" }}

      - run: npm ci

      - save_cache:
          name: Save Package Cache
          key: packages-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules/

      - run: npm run all
